[package]
name = "cbadv"
version = "1.4.3"
edition = "2021"
description = "Asynchronous Coinbase Advanced REST and WebSocket API"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Ohkthx/cbadv-rs"
repository = "https://github.com/Ohkthx/cbadv-rs"
keywords = ["trading", "coinbase", "coinbasepro", "coinbaseadvanced", "crypto"]
categories = ["api-bindings", "cryptocurrency"]
include = ["*/**.rs"]

[features]
default = ["config"]
full = ["config"]
config = ["dep:toml"]

[dependencies]
# Core dependencies
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
tokio = { version = "1.12.0", features = ["full"] }

# Cryptography and signing
hmac = "0.12.1"
sha2 = "0.10.6"
hex = "0.4.3"

# Serialization and configuration
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
toml = { version = "0.7.3", optional = true }

# WebSocket support
tokio-tungstenite = { version = "0.19.0", features = ["native-tls"] }
futures-util = "0.3.28"

# Utilities
uuid = { version = "1.3.4", features = ["v4", "fast-rng", "macro-diagnostics"] }
chrono = "0.4.31"
num-traits = "0.2.17"
base64 = "0.21.7"
ring = "0.17.7"
rand = "0.8.5"
openssl = "0.10.63"

[[example]]
name = "account_api"
path = "examples/account_api.rs"
required-features = ["config"]

[[example]]
name = "product_api"
path = "examples/product_api.rs"
required-features = ["config"]

[[example]]
name = "fee_api"
path = "examples/fee_api.rs"
required-features = ["config"]

[[example]]
name = "order_api"
path = "examples/order_api.rs"
required-features = ["config"]

[[example]]
name = "public_api"
path = "examples/public_api.rs"
required-features = ["config"]

[[example]]
name = "sandbox_api"
path = "examples/sandbox_api.rs"
required-features = ["config"]

[[example]]
name = "portfolio_api"
path = "examples/portfolio_api.rs"
required-features = ["config"]

[[example]]
name = "websocket"
path = "examples/websocket.rs"
required-features = ["config"]

[[example]]
name = "watch_candles"
path = "examples/watch_candles.rs"
required-features = ["config"]

[[example]]
name = "custom_config"
path = "examples/custom_config.rs"
required-features = ["config"]

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1
opt-level = 3

[dev-dependencies]
tokio-test = "0.4.2"
assert-json-diff = "2.0.1"

[badges]
travis-ci = { repository = "ohkthx/cbadv-rs", branch = "main" }
maintenance = { status = "actively-developed" }
