[package]
name = "cbadv"
license = "MIT"
version = "1.3.0"
edition = "2021"
description = "Asynchronous Coinbase Advanced REST and WebSocket API"
readme = "README.md"
homepage = "https://github.com/Ohkthx/cbadv-rs"
repository = "https://github.com/Ohkthx/cbadv-rs"
keywords = ["trading", "coinbase", "coinbasepro", "coinbaseadvanced", "crypto"]
include = ["*/**.rs"]

[features]
default = []
full = ["config"]
config = ["dep:toml"]

[[example]]
name = "account_api"
path = "examples/account_api.rs"
required-features = ["config"]

[[example]]
name = "product_api"
path = "examples/product_api.rs"
required-features = ["config"]

[[example]]
name = "fee_api"
path = "examples/fee_api.rs"
required-features = ["config"]

[[example]]
name = "order_api"
path = "examples/order_api.rs"
required-features = ["config"]

[[example]]
name = "websocket"
path = "examples/websocket.rs"
required-features = ["config"]

[[example]]
name = "watch_candles"
path = "examples/watch_candles.rs"
required-features = ["config"]

[[example]]
name = "custom_config"
path = "examples/custom_config.rs"
required-features = ["config"]


[dependencies]
reqwest = { version = "0.11", features = ["json"] } # Making HTTP requests.
futures = { version = "0.3" } # Async / await blocks
tokio = { version = "1.12.0", features = ["full"] } # Async runtime
hmac = { version = "0.12.1" } # Signing requests with a signature.
sha2 = { version = "0.10.6" } # Signing requests with a signature.
hex = { version = "0.4.3" } # Convert signature for HTTP headers.
serde_json = { version = "1.0.96" } # Converting Configuration file and Objects from API.
serde = { version = "1.0.163", features = ["derive"] } # Converting Configuration file and Objects from API.
toml = { version = "0.7.3", optional = true } # Creating Configuration file.
uuid = { version = "1.3.4", features = ["v4", "fast-rng", "macro-diagnostics"] } # Create Client ID for orders.
async-recursion = { version = "1.0.4" } # Recursive async functions require this.
tokio-tungstenite = { version = "0.19.0", features = ["native-tls"] } # WebSocket requirement.
futures-util = { version = "0.3.28" } # Required for the WebSocket client.
chrono = { version = "0.4.31" } # Used to pass current candle timestamp to candle watcher.
